#!/bin/bash
# script that will display information about subdomains.

display_info() {
  local domain="$1"
  local subdomain="$2"

  local result=$(dig +short "$subdomain.$domain")
  local record_type=$(echo "$result" | awk '{print $1}')
  local destination=$(echo "$result" | awk '{print $2}')

  echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

if [ "$#" -lt 1 ] || [ "$#" -gt 2 ]; then
  echo "Usage: $0 <domain> [subdomain]"
  exit 1
fi

domain="$1"
subdomain="$2"

if [ -z "$subdomain" ]; then
  display_info "$domain" "www"
  display_info "$domain" "lb-01"
  display_info "$domain" "web-01"
  display_info "$domain" "web-02"
else
  display_info "$domain" "$subdomain"
fi

