#!/usr/bin/env bash
# Install nginx web server
apt-get update
apt-get install -y nginx
echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html
sed -i '/server_name _;/a \
\
    location /redirect_me {\
    return 301 https://github.com/Mennatalla-Khougha; \
    } \
\
    error_page 404 /404.html; \
    location =/404.html { \
    root /var/www/html; \
    internal; \
    }' /etc/nginx/sites-available/default
service nginx restart
