#!/usr/bin/env bash
# Install load balancer
sudo apt update
sudo apt install -y haproxy

sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak

echo "  frontend web 
        bind *:80
        default_backend web

    backend web
        server web-01 100.25.111.125:80 check
        server web-02 34.207.190.218:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
